name: SimpleShop
main: xyz.acrylicstyle.simpleshop.SimpleShop
version: 1.0.0-SNAPSHOT
api-version: 1.13
depend:
  - Vault
softdepend:
  - LifeCore
commands:
  shop:
    permission: simpleshop.command.shop
    aliases: [ss, simpleshop]
  sell:
    permission: simpleshop.command.sell
permissions:
  simpleshop.command.shop:
    description: Allows you to open the shop
    default: true
  simpleshop.command.sell:
    description: Allows you to sell items
    default: true
